baseURL = "https://abhishekkumar.xyz/"
languageCode = "en-us"
title = "Abhishek Kumar"
theme = "warbird"
paginate = 5

[params]
  description = "thoughts, projects and notes"
  author = "Abhishek Kumar"
  github = "https://github.com/abhkpr"
  notes = "https://abhkpr.github.io/notes"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "blog"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 4
  [[menu.main]]
    name = "research"
    url = "/research"
    weight = 4
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 5
  [[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 6
